### ISSUE TITLE
Typo on About view

### ISSUE THREAD

**Issue by fetimo** [leif-app/leif-desktop#20]
Small typo on About view where 'Dekstop' should be 'Desktop'

![Screenshot_20221128_132444](https://user-images.githubusercontent.com/596629/204291524-3f907e7d-d2c7-4e37-98f9-1f22ed0c63c8.png)

**Comment by scharsig** [comment]
![image](https://user-images.githubusercontent.com/16097915/205505097-1bfbeb0c-6637-44bc-a262-6cceeacb3b98.png)
Done
