### ISSUE TITLE
Typo in unit

### ISSUE THREAD

**Issue by fetimo** [leif-app/leif-desktop#21]
'grCO2' unit should be 'gCO₂e', same goes for the tray.

![Screenshot_20221128_132424](https://user-images.githubusercontent.com/596629/204291787-88e448ed-6e0f-4a75-844e-192f620cbd98.png)

**Comment by scharsig** [comment]
![image](https://user-images.githubusercontent.com/16097915/205505047-03bc4568-b69a-4d61-8466-cf00ce762688.png)
![image](https://user-images.githubusercontent.com/16097915/205505063-6800f77e-f61f-4927-83ab-98ecb4a13495.png)
Done.
